### PR TITLE
Added docker

### PR DESCRIPTION
**Pull request by maZahaca**
Add an ability to build docker images for goose-parser with different environments

### CODE REVIEW

**Comment by maZahaca** [comment]
@jifeon you can find results of this scripts here: https://hub.docker.com/r/redcode/goose-parser/tags/

**Comment by jifeon** [comment]
pls do not forget to remove branches

**Comment by maZahaca** [comment]
Thanks God! We have you :)

**Comment by maZahaca** [comment]
🐗

**Comment by jifeon** [comment]
🐗

**Pull request merged**
