### PR TITLE
preActions

### PR DESCRIPTION
**Pull request by maZahaca**
- Added preActions;
- Fixed parsing of root simple and collection types;
- Improved tests

#18

### CODE REVIEW

**Comment by maZahaca** [comment]
for review @jifeon

**Comment by jifeon** [comment]
have not seen documentation for preActions. What is it?

**Comment by maZahaca** [comment]
I will add a documentation for that.
Generally this is a way to execute some actions before parsing process (for now this is the same as actions with flag `once`). But they were moved out from parsing rules, because they don't have any relation to parsing, they care about to place user to land user on prepared page. What do you think @jifeon ?

**Comment by maZahaca** [comment]
@jifeon added docs

**Comment by jifeon** [comment]
looks great! maybe name it just `actions`? We don't need different name because it's already outside `rules`

**Comment by jifeon** [comment]
I mean:

```js
parse({
  actions: [], // <- it even looks like actions "before" rules
  rules: {}
})
```

**Comment by maZahaca** [comment]
yep. it's better for goose

**Pull request merged**
